{
  "comments": [
    {
      "key": {
        "uuid": "b8880d24_d9b8c03e",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 60,
      "author": {
        "id": 68
      },
      "writtenOn": "2018-11-09T18:48:37Z",
      "side": 1,
      "message": "Looks like pattern defaults to None in the func def.",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "b9365441_8bd361b6",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 60,
      "author": {
        "id": 8
      },
      "writtenOn": "2018-11-09T18:55:04Z",
      "side": 1,
      "message": "Nope it doesn\u0027t. It will return a tuple () we want to ensure it\u0027s None.",
      "parentUuid": "b8880d24_d9b8c03e",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "bc1f889b_7e0a969a",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 64,
      "author": {
        "id": 68
      },
      "writtenOn": "2018-11-09T18:51:05Z",
      "side": 1,
      "message": "The potential http error is caught inside the function now correct?",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "e62aa889_726f7071",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 64,
      "author": {
        "id": 68
      },
      "writtenOn": "2018-11-09T18:52:31Z",
      "side": 1,
      "message": "Possible relevant to change this to catch an IO Exception since there are file ops going on?",
      "parentUuid": "bc1f889b_7e0a969a",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "c14b3e09_3fb2b2f3",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 64,
      "author": {
        "id": 8
      },
      "writtenOn": "2018-11-09T18:55:04Z",
      "side": 1,
      "message": "Yes. We need to catch it here so that the cli can return the log.error()",
      "parentUuid": "bc1f889b_7e0a969a",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "6e8e3748_9a31b221",
        "filename": "lftools/cli/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 64,
      "author": {
        "id": 8
      },
      "writtenOn": "2018-11-09T18:55:04Z",
      "side": 1,
      "message": "I don\u0027t know. Maybe?",
      "parentUuid": "e62aa889_726f7071",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "27384bd4_8dc90d72",
        "filename": "lftools/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 110,
      "author": {
        "id": 214
      },
      "writtenOn": "2018-11-12T01:24:17Z",
      "side": 1,
      "message": "What if wrong permission? Overkill?",
      "range": {
        "startLine": 110,
        "startChar": 12,
        "endLine": 110,
        "endChar": 18
      },
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "ed69838d_b4b9abb6",
        "filename": "lftools/deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 154,
      "author": {
        "id": 214
      },
      "writtenOn": "2018-11-12T01:24:17Z",
      "side": 1,
      "message": "Any exceptions possible? Wrong permission?",
      "range": {
        "startLine": 154,
        "startChar": 15,
        "endLine": 154,
        "endChar": 21
      },
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "011d61ae_aa9e936e",
        "filename": "tests/test_deploy.py",
        "patchSetId": 10
      },
      "lineNbr": 117,
      "author": {
        "id": 214
      },
      "writtenOn": "2018-11-12T01:24:17Z",
      "side": 1,
      "message": "Test case for missing directory for destination?",
      "revId": "0fcafa53a92105954afa47397d6b815bd9cc9f5d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": false
    }
  ]
}