{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "7be41d87_468d4542",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 214
      },
      "writtenOn": "2022-05-25T05:01:11Z",
      "side": 1,
      "message": "Get the following error when I try it.\n\n(dev) [bengt@fedora lftools]$ lftools jenkins get-credentials\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nurllib3.exceptions.NewConnectionError: \u003curllib3.connection.HTTPSConnection object at 0x7f38511d2110\u003e: Failed to establish a new connection: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host\u003d\u0027localhost\u0027, port\u003d8080): Max retries exceeded with url: /crumbIssuer/api/json (Caused by NewConnectionError(\u0027\u003curllib3.connection.HTTPSConnection object at 0x7f38511d2110\u003e: Failed to establish a new connection: [Errno 111] Connection refused\u0027))\n\nDuring handling of the above exception, another exception occurred:\n\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host\u003d\u0027localhost\u0027, port\u003d8080): Max retries exceeded with url: /crumbIssuer/api/json (Caused by NewConnectionError(\u0027\u003curllib3.connection.HTTPSConnection object at 0x7f38511d2110\u003e: Failed to establish a new connection: [Errno 111] Connection refused\u0027))\n(dev) [bengt@fedora lftools]$\n",
      "revId": "6179e0fd0a739339ca2a8522c8dcbe16b3b1c59d",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09"
    }
  ]
}